### ISSUE TITLE
Extremely large numbers are not properly outputted and overflow too easily

### ISSUE THREAD

**Issue by fionafibration** [MiningPotatoes/Ohm#8]
I am attempting to write a 1024 bit RSA program in Ohm, but unfortunately I am limited to only 8 bits for the exponent for it to not overflow. Even then, the format in which the output is displayed prevents me from accessing most of the least significant digits, (it uses the 1.1202002e+62 format) thus preventing me from decrypting. Is there any chance of a fix for which the code could handle integers of arbitrary size? (ie. like Python's integers and floats) 
This would be very helpful for cryptography.

P.S. your language is absolutely godly and deserves widespread recognition.

**Comment by nickbclifford** [comment]
The issue here is that both integers and floats are represented as floats internally because Ohm treats strings and numbers the same. If I had everything coerced to integer, passing 34.6 and 6.3 to the `+` component would give you 40 instead of 40.9. 
I don't think I'll be able to fix the limited precision issues; however, using the `ì` component to convert the argument to an _integer_ on the stack instead of a _float_ might help the output issue.

Thanks for reaching out!

**Comment by fionafibration** [comment]
Ok, thanks for your help!

**Comment by nickbclifford** [comment]
Actually, I recently realized that I could fix the precision issues by changing Ohm to use arbitrary-precision [BigDecimals](https://ruby-doc.org/stdlib-2.4.2/libdoc/bigdecimal/rdoc/BigDecimal.html) instead of double-precision floats. I'll try to work on that soon.

**Comment by fionafibration** [comment]
That's what I was thinking... I read a bit about it.

**Comment by nickbclifford** [comment]
Alright, this should be fixed for _good_ in #11. Let me know if you have any other issues/requests!
